substantiivi = input("substantiivi: ")
verbi = input("verbi perusmuodossa: ")
adjektiivi = input("adjektiivi: ")
komparatiivi = input("komparatiivi: ")
superlatiivi = input("superlatiivi: ")

print("He grabbed the ", substantiivi, " and threw it across the room.")
print("Then he was about to ", verbi, " and shake the ", substantiivi)
print("The ", substantiivi, " was very ", adjektiivi, " after that.")
print("Although the thing next to it was so much ", komparatiivi, " than the ", substantiivi)
print("Despite everything that happened that day, it was the ", superlatiivi, " thing ever.")